### ISSUE TITLE
[calamares]: locales (like language, region and timezone/format) not set correctly or fully

### ISSUE THREAD

**Issue by star-buck** [blue-systems/maui-netrunner-issues#12] opened 2016-07-24 15:14 UTC
maybe calamares needs to do this the same way as ubiquity and set correctly the locale, or its a problem on maui/netrunner side?

**Comment by llelectronics** [comment] 2016-07-24 16:08
I thought we fixed this last month with cala 2.2.3

**Comment by star-buck** [comment] 2016-07-24 16:15
its says running cala 2.3 on the netrunner ISO and arm

**Comment by llelectronics** [comment] 2016-07-24 16:16
Is /etc/default/locale setup correct? E.g. LANG=de_DE.UTF-8

**Comment by star-buck** [comment] 2016-07-24 16:27
on arm: US.UTF-8
the thing is:
- i leave language to english for translations
- then set Berlin for location but the locale doesnt change accordingly... i would suggest the locale or at least timezone would change to wherever the location is set to, so english or spanish people in germany can choose langaue independent from locale/timezone...
wasnt that like this at some point?

**Comment by llelectronics** [comment] 2016-07-24 16:37
Never had a problem with it when setting English and Berlin as timezone. 
Or did you change timezone after installing?

**Comment by star-buck** [comment] 2016-07-24 16:43
nope. it simply isnt set correctly after installing netrunner or maui with cala, time is -2 hours off and displayed as 4:41pm.

**Comment by llelectronics** [comment] 2016-07-24 17:05
Ah ok. Thats a bug I reported already. (can't find the link however I think it was closed as not reproducable). But if you go to the time settings (right click on the digital clock) it should show the correct time aswell as when you add a analog clock as widget. 
So I think it is a bug in the digital clock widget

**Comment by star-buck** [comment] 2016-07-24 17:09
well, i will try with maui again, but as far as i can tell on netrunner, not really...

**Comment by star-buck** [comment] 2016-07-24 18:03
maui-neon using ubiquity: as soon as i set the timezone on that installer page, the panel clock is set to correct time (it still shows PM, but thats due to format english langauge i guess).
So as it looks, its calamares?

**Comment by star-buck** [comment] 2016-07-24 19:05
maui-neon also sets this, so even the format of 24:00 in clock panel is right after reboot:
![screenshot_20160724_210234](https://cloud.githubusercontent.com/assets/840070/17085828/4679d1e8-51e2-11e6-854b-4a8b8547ac63.png)

**Comment by teo** [comment] 2016-07-26 16:14
The way I see it, there are two separate issues in this report, please correct me if I got it wrong:
1) the Calamares locale setting defaults to the chosen language rather than to the chosen timezone, and
2) Calamares only sets the LANG variable and not the other ones.

I've already pushed a fix for issue (2), but not for issue (1), which is more complex.

I had initially chosen to have the locale default to the UI language because since we do not do any geolocation, this is the only locale data we can work with. I've investigated the option of having the locale setting default to the chosen timezone, but this presents some obstacles.
a) While every translated language can be associated with a locale, this is not necessarily true for timezones. The only relevant data we can get from a timezone is a country code associated with it (this can be read from zone.tab, if the distro ships this file). Then, from this country code it should be possible to get a country - not necessarily the most reliable source, but so far so good.
b) Even if we have a country, not every country is associated with a single locale, with the risk of confusing (or even offending) the user. For instance, what happens if the user's timezone choice puts him or her in Switzerland? Should we default to de_CH, fr_CH or it_CH? Another example is Belgium: whether we pre-select French or Flemish, we're offering a bad default for half the population.

Geolocation might help with this, because even with coarse IP-based geolocation we'd probably get a finer grained location than just a timezone code. However, I wouldn't go into geolocation without also porting the map widget to Marble (which is something that needs to be done anyway, with or without geolocation, as soon as possible because the current widget looks very tiny on high-DPI displays).

I can also take a deeper look at what Ubiquity is doing, just in case they have some guesswork and special-casing we can reuse, or maybe some other way to solve situations like Switzerland and Belgium, but I'm not certain that for most users the end result would be better than defaulting to the UI language as we do now.

**Comment by star-buck** [comment] 2016-07-26 16:38
Ubiquity defines various variables mixed, see above. The result under kde
is a better set clock, still using the language english default though.

**Comment by teo** [comment] 2016-07-27 06:54
@star-buck I see. We could make the LANG variable default to the Calamares UI language, and all the other LC_ variables would somehow be guessed from the timezone. I'm looking at what Ubiquity does.

**Comment by star-buck** [comment] 2016-07-27 09:24
Guessed? 
I picked Berlin in ubiquity and thats simply De-de for everything but language like in the above example... do i miss whats so hard to set everything else but language and keyboard according to the place one picked? its at least 100% more accurate than leaving everything out.

**Closed** 2016-08-10 09:03 UTC
